apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: tvyo9wlps-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/tvyo9wlps-dotnet-basic-gitops